package python.multiplatform.gradle.stubs

import python.multiplatform.gradle.model.DeclarationModel
import python.multiplatform.gradle.model.DeclaredParameter

/**
 * The stub product: `docs/design/pyi-generation-design.md` §5.3's Kotlin-FQN stubs, rendered from the
 * declaration model.
 *
 * One `def` per bound declaration, in the module the runtime publishes it onto, under the Kotlin
 * names. The binder never exports a Kotlin namespace under another name (AGENTS.md §12 rule 1), so
 * there is no second, renamed product: a `pythonx` module is a real Python package that imports
 * these modules and makes them Pythonic, and its own stubs are its own.
 *
 * Returns *relative path to file content*, so nothing here touches a disk and every assertion in
 * `PyiRenderingTest` is over text. `PythonStubsTask` is the only thing that writes.
 */

private const val HEADER = "# GENERATED by python-multiplatform-gradle-plugin. Do not edit."

/**
 * The 1:1 product: one `def` per `UpcallTable` key, in the module the runtime publishes it onto.
 *
 * ### The types are the boundary's, not the declaration's
 *
 * `PythonProxySource.renderOne` publishes `setattr(_pm_module('androidx.compose.foundation.layout'),
 * 'padding__Dp', f)` where `f` is `def _pm_f_7(a0, a1)`, and `UpcallTrampoline` marshals a `Dp`
 * argument as a raw float and a `Modifier` return as a `HandleTable` integer. So this product
 * annotates `float` and `int`: that is what the module accepts and returns, and
 * `docs/design/pyi-generation-design.md` §7 lists the handle-to-proxy wrapping that would make it
 * `Modifier` as *not yet done*. Saying `-> Modifier` here would be the exact lie that section warns
 * about. The Kotlin signature goes in the docstring, which is where a reader wants it and where no
 * checker can act on it.
 *
 * ### Parameters

The runtime accepts keyword arguments by the **Kotlin parameter names** and honours Kotlin defaults
(an omitted defaulted parameter takes the Kotlin default). So the extension receiver stays
positional-only (`receiver: ..., /`) and every declared parameter is positional-or-keyword under its
Kotlin name, with `= ...` when the declaration has a default. Two cases cannot be written as a
keyword in `.pyi` syntax: a name that is not a Python identifier or is a Python keyword (`in`, `is`,
`from`), and an unknown name (a Java class without `-parameters`, `parameterNamesKnown == false`).
Those parameters -- and every parameter before one, to keep the stub valid -- are positional-only,
the unwritable one spelled `__a<index>`. No renamed spelling is invented.
 */
internal fun renderKotlinFqnStubs(declarations: List<DeclarationModel>): Map<String, String> {
    val byModule = declarations
        .filter { it.bindingName != null && !it.isSuspend }
        .groupBy { it.bindingName!!.substringBeforeLast('.') }
    return byModule.toSortedMap().mapValues { (_, entries) ->
        buildString {
            appendLine(HEADER)
            appendLine()
            entries.sortedBy { it.bindingName }.forEach { declaration ->
                appendLine(renderKotlinFqnDef(declaration))
                appendLine()
            }
        }
    }.mapKeys { (module, _) -> module.replace('.', '/') + "/__init__.pyi" }
}

private fun renderKotlinFqnDef(declaration: DeclarationModel): String {
    val leaf = declaration.bindingName!!.substringAfterLast('.')
    if (declaration.kind == "STATIC_GETTER") {
        return buildString {
            appendLine("$leaf: ${boundaryAnnotation(declaration.returnBoundaryTag)}")
            append("\"\"\"Kotlin: ${kotlinSignatureOf(declaration)}\"\"\"")
        }
    }
    val signature = renderParameters(declaration)
    return buildString {
        appendLine("def $leaf$signature -> ${boundaryAnnotation(declaration.returnBoundaryTag)}:")
        appendLine("    \"\"\"Kotlin: ${kotlinSignatureOf(declaration)}\"\"\"")
        append("    ...")
    }
}

/**
 * `python.multiplatform.reflection.TypeTag` to the Python type that actually crosses.
 *
 * `OBJECT` is `int` because it is: `UpcallTrampoline.marshalResult` puts the Kotlin object in
 * `HandleTable` and hands Python the resulting integer, and `PythonProxySource`'s KDoc records that
 * such a handle "is the caller's to release".
 */
private fun boundaryAnnotation(tag: String?): String = when (tag) {
    "INT", "OBJECT" -> "int"
    "FLOAT" -> "float"
    "BOOLEAN" -> "bool"
    "STRING" -> "str"
    "BYTES" -> "bytes"
    "UNIT" -> "None"
    else -> "object"
}

/** What the docstring says: the declaration as Kotlin wrote it, which is the information the
 * annotations above deliberately do not carry. */
private fun kotlinSignatureOf(declaration: DeclarationModel): String {
    val owner = declaration.receiver?.qualifiedName ?: declaration.owner
    val parameters = declaration.parameters.joinToString(", ") { parameter ->
        val type = parameter.type.qualifiedName + if (parameter.type.isNullable) "?" else ""
        if (declaration.parameterNamesKnown && parameter.name != null) "${parameter.name}: $type" else type
    }
    return "$owner.${declaration.simpleName}($parameters): ${declaration.returnType.qualifiedName}"
}

/** Python's hard keywords (`keyword.kwlist`): none of these can be a parameter name. */
private val PYTHON_KEYWORDS = setOf(
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
    "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
    "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
    "try", "while", "with", "yield",
)

private fun isWritableName(name: String?, receiverPresent: Boolean): Boolean =
    name != null &&
        name !in PYTHON_KEYWORDS &&
        !(receiverPresent && name == RECEIVER_NAME) &&
        (name[0] == '_' || name[0].isLetter()) &&
        name.all { it == '_' || it.isLetterOrDigit() }

private const val RECEIVER_NAME = "receiver"

/**
 * `(receiver: T, /, a: A, b: B = ...)`, or `(__a0: A, x: B, /)` when a name cannot be written.
 *
 * Python rejects a parameter without a default after one with a default, and Kotlin allows it
 * (`padding(start = 0.dp, top: Dp)`), so a default is marked only when no required parameter
 * follows it. The stub then never promises an omission the syntax cannot express.
 */
private fun renderParameters(declaration: DeclarationModel): String {
    val hasReceiver = declaration.receiver != null
    val parameters = declaration.parameters
    val writable = parameters.map { declaration.parameterNamesKnown && isWritableName(it.name, hasReceiver) }
    // Everything up to and including the last unwritable name is positional-only.
    val positionalOnlyEnd = writable.indexOfLast { !it }
    val lastRequired = parameters.indexOfLast { !it.declaresDefault }

    val rendered = mutableListOf<String>()
    // The extension receiver is the runtime's first positional argument and has no Kotlin name.
    if (hasReceiver) rendered += "$RECEIVER_NAME: " + boundaryAnnotation(declaration.receiverBoundaryTag)
    if (hasReceiver && positionalOnlyEnd < 0 && parameters.isNotEmpty()) rendered += "/"
    parameters.forEachIndexed { index, parameter ->
        val name = if (writable[index]) parameter.name!! else "__a$index"
        val default = if (parameter.declaresDefault && index > lastRequired) " = ..." else ""
        rendered += "$name: " + boundaryAnnotation(parameter.boundaryTag) + default
        if (index == positionalOnlyEnd) rendered += "/"
    }
    if (rendered.isEmpty()) return "()"
    if (parameters.isEmpty() && hasReceiver) rendered += "/"
    return "(" + rendered.joinToString(", ") + ")"
}
